### ISSUE TITLE
Export MS access schema

### ISSUE THREAD

**Issue by dnnrly** [ricks03/TotalHost#1]
**Is your feature request related to a problem? Please describe.**
This is a suggestion to help people that have a passing interest in this project but do not have MS Access.

**Describe the solution you'd like**
Manually export the schema and add it to the repo in plain text/SQL.

**Describe alternatives you've considered**
N/A

**Additional context**
Who knows, maybe you'll get some contributions. 😁

**Comment by ricks03** [comment]
There aren't enough people interested to make this suggestion worthwhile effort vs. return. And this is mostly a self-hosted project.

**Comment by ricks03** [comment]
What the heck, I found an easy way to do it. done.
